# Generated by Django 3.2.5 on 2021-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_authorsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='sticker',
            field=models.CharField(max_length=3),
        ),
    ]
