# Generated by Django 3.2.5 on 2021-08-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_user_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorSubscriber',
        ),
    ]
