# Generated by Django 3.2.5 on 2021-08-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_delete_authorsubscriber'),
        ('authapp', '0007_alter_user_refresh_token'),
    ]

    operations = [
    ]
