# Generated by Django 3.2.5 on 2021-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quote', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
